class UserRequest:
    """
    A basic value storage for all APIs storing the necessary request data
    in a friendly and accessible way.
    """

    def __init__(self):
        self.username = None
        self.connection_id = None
        self.request_type = None
        self._parameters = None
        self.request_id = None

    @property
    def parameters(self):
        """
        Creates a new copy of the given parameter dictionary to avoid lower functions
        changing it.
        :return: Shallow copy parameters
        """
        return self._parameters.copy()

    @parameters.setter
    def parameters(self, value):
        self._parameters = value


class ApiResponse:
    """
    A basic storage for responses generated by the API to avoid passing around complex
    tuples or dictionaries of unknown structure.
    """

    def __init__(self, request: UserRequest):
        self.request_type = request.request_type
        self.request_parameters = request.parameters
        self.request_id = request.request_id
        self.status_code = None
        self.message_type = None
        self.content = None
